### ISSUE TITLE
Lib update todo

### ISSUE THREAD

**Issue by ed-xmos** [xmos/lib_ethernet#59]
- [ ]  AN docs 
- [ ]  Add XS3 support to tests 
- [ ]  Review and fix issues as appropriate
- [ ]  Hardware regression test?
- [ ]  Remove xcommon for example but add legacy build test 
- [ ] Move requirements to /tests
- [ ] Add test for legacy (xcommon) build

**Comment by ed-xmos** [comment]
This project is now covered by Jira in XMOS
